### ISSUE TITLE
`isPending`'s value is unclear after deactivate()

### ISSUE THREAD

**Issue by mingyc** [WICG/unload-beacon#11]
> isPending: whether or not the beacon has started the sending process.

Given the current description, we can infer the following value

* after constructor: true
* after sendNow(): false
* after sendNow() but the request fail: false
* after deactivate(): ??

It's unclear whether `isPending` should be `false` or `undefined`.

**Comment by fergald** [comment]
There was a thread in one of the design docs suggesting that it be replaced with `canSetData` or something like that. This seems reasonable to me. If people need to be able to tell why it's false (e.g. sent vs deactivated) we could add other boolean accessors but it does seem like the app itself should know if it deactivated the beacon.

**Comment by philipwalton** [comment]
I believe `isPending` should be `false` in the deactivated case. I agree with @fergald that the app should be able to know if it deactivated the beacon.

**Comment by fergald** [comment]
@philipwalton Any opinions on the naming? It sounds like you are agreeing that the semantic is essentially `canSetData`, should we name it that?

**Comment by philipwalton** [comment]
> @philipwalton Any opinions on the naming...

I like the name `isPending` because it's very clear, though I agree that I'd probably only ever use it in the negative, e.g.`if (!beacon.isPending) {...}`, so maybe that's a sign that another name is better.

Also, according to the [TAG's Design Principles guide](https://www.w3.org/TR/design-principles/#naming-booleans), boolean properties should not be prefixed with `is` (only boolean methods, e.g. `isPending()`), so the name should probably be changed regardless.

> It sounds like you are agreeing that the semantic is essentially `canSetData`, should we name it that?

I'm not particularly fond of the name `canSetData` because (at least to me) it doesn't answer the primary question which is whether or not the data was sent. It requires knowledge from the user that you can only set data in that case (assuming that remains true), so I think this ambiguity is not ideal.

I think my preference is `.pending`.

Alternatively, I know that a granular state enum (incl. 'sending', 'sent', 'failed') were previously rejected, but I could see a less-granular state enum potentially working well, e.g. `.state = 'pending' | 'sent' | 'deactivated'`.
